# Generated by Django 3.2.3 on 2021-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released_on', models.DateTimeField(blank=True, null=True)),
                ('artists', models.ManyToManyField(to='catalog.Artist')),
            ],
        ),
    ]
