# Generated by Django 3.2.3 on 2021-12-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to='artists_downloads'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
